### ISSUE TITLE
Support for transformer-based model.

### ISSUE THREAD

**Issue by geekinglcq** [numpee/CKA.pytorch#1]
Hello, I am glad to see your excellent job on the CKA calculation in ResNet and wonder if you will add support for the transformer-based models such as BERT?

**Comment by numpee** [comment]
Hi @geekinglcq, 
Could you perhaps link me to a model you'd like to calculate CKA on?
You can also set your own layer types, as shown under the **Advanced Usage** section in the [example notebook](https://github.com/numpee/CKA.pytorch/blob/main/example.ipynb).

**Comment by geekinglcq** [comment]
Thank you～
